version: 1.0.{build}-{branch}

skip_commits:
  files:
    - 'azure-pipelines.yml'
    - 'README.md'

install:
  - set PATH=C:\Ruby26-x64\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - rails db:migrate RAILS_ENV=test
