name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build Application
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install
      - name: Run Test
        env:
          RAILS_ENV: test
        run: |
          bin/rake test
          bin/rake test:system
