name: Ruby

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres


on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
        - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{ env.POSTGRES_DB}}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.13.0
      
      - name: install sqlite
        run: sudo apt-get -yqq install libsqlite3-dev libpq-dev build-essential libcurl4-openssl-dev
      
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build Application
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install
      
      - name: Create database
        env:
          RAILS_ENV: test
        run: |
          bundler exec rails db:create
          bundler exec rails db:migrate
      
      - name: Run tests
        run: bundler exec rake

  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Install Rubocop
        run: gem install rubocop
      - name: Check code
        run: rubocop
