name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: install sqlite
        run: |
          sudo apt-get -yqq install libsqlite3-dev libpq-dev
      - name: Build Application
        run: |
          gem install bundler
          bundle install
          bundle exec rails db:setup
      - name: Run Test
        env:
          RAILS_ENV: test
        run: |
          bin/rake test
          bin/rake test:system
